name: Python Hello World
on: [push]
permissions:
      contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f .github/workflows/jupyter-cleaner/requirements.txt ]; then pip install -r .github/workflows/jupyter-cleaner/requirements.txt; fi
      - name: nbconvert the notebook
        run: |
           jupyter nbconvert "Untitled.ipynb" --to html
      - name: clear notebook output
        run: |
           jupyter nbconvert "Untitled.ipynb" --clear-output
      - name: Commit and push
        run: |
                git config --global user.name github-actions
                git config --global user.email github-actions@github.com
                git add --all
                git commit -m "commit htmls"
                git push
                ls
