name: Python Hello World
on: [push]
permissions:
      contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f .github/workflows/requirements-jupyter-cleaner.txt ]; then pip install -r .github/workflows/requirements-jupyter-cleaner.txt; fi
      - name: Echo added/modified files
        run: |
            echo "Added+Modified:"
            echo "${{ steps.abc.outputs.added_modified }}"
            for OUTPUT in ${{steps.abc.outputs.added_modified}}
            do
                  if [ "$OUTPUT" == "*.ipynb" ]  # only try to convert notebooks
                    then
                     echo $OUTPUT
                     jupyter nbconvert "$OUTPUT" --to html
                     jupyter nbconvert "$OUTPUT" --clear-output
                    fi
            done
            echo "~~~~~~~~~~~~"
            ls -R
      - name: Commit and push
        run: |
                git config --global user.name github-actions
                git config --global user.email github-actions@github.com
                git add --all
                git commit -m "commit htmls"
                git push
                ls
