name: Python Hello World
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f .github/workflows/requirements.txt ]; then pip install -r .github/workflows/requirements.txt; fi
      - name: nbconvert the notebook
        run: |
           jupyter nbconvert "Untitled.ipynb" --to html
      - name: clear notebook output
        run: |
           jupyter nbconvert "Untitled.ipynb" --clear-output
      - name: Create and push test file
        run: |
                pwd
                ls
                touch testfile.txt
               
                ls
